# Generated by Django 5.0.6 on 2024-05-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_category_pdf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf.category'),
        ),
    ]
